# Generated by Django 4.1.7 on 2023-03-06 16:02

import books.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "original_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ua", "Ukrainian"),
                            ("fr", "French"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "type_book",
                    models.CharField(
                        choices=[("translated", "Переклад"), ("origin", "Авторська")],
                        max_length=40,
                    ),
                ),
                ("age_restrictions", models.BooleanField(default=False)),
                ("is_ready", models.BooleanField(default=False)),
                ("created", models.DateField(auto_now=True)),
                ("last_edit", models.DateField(auto_now_add=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "is_approved",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fund_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre_name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first",
                    models.ImageField(
                        blank=True, null=True, upload_to=books.models.upload_to
                    ),
                ),
                (
                    "second",
                    models.ImageField(
                        blank=True, null=True, upload_to=books.models.upload_to
                    ),
                ),
                (
                    "third",
                    models.ImageField(
                        blank=True, null=True, upload_to=books.models.upload_to
                    ),
                ),
                (
                    "fourth",
                    models.ImageField(
                        blank=True, null=True, upload_to=books.models.upload_to
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="AccessBook",
            fields=[
                (
                    "comment_book",
                    models.CharField(
                        choices=[
                            ("all", "Усі"),
                            ("admin", "Модератори"),
                            ("none", "Ніхто"),
                        ],
                        default="all",
                        max_length=40,
                    ),
                ),
                (
                    "comment_chapter",
                    models.CharField(
                        choices=[
                            ("all", "Усі"),
                            ("admin", "Модератори"),
                            ("none", "Ніхто"),
                        ],
                        default="all",
                        max_length=40,
                    ),
                ),
                (
                    "comment_page",
                    models.CharField(
                        choices=[
                            ("all", "Усі"),
                            ("admin", "Модератори"),
                            ("none", "Ніхто"),
                        ],
                        default="all",
                        max_length=40,
                    ),
                ),
                (
                    "download",
                    models.CharField(
                        choices=[
                            ("all", "Усі"),
                            ("admin", "Модератори"),
                            ("none", "Ніхто"),
                        ],
                        default="all",
                        max_length=40,
                    ),
                ),
                (
                    "estimate",
                    models.CharField(
                        choices=[
                            ("all", "Усі"),
                            ("admin", "Модератори"),
                            ("none", "Ніхто"),
                        ],
                        default="all",
                        max_length=40,
                    ),
                ),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="access",
                        serialize=False,
                        to="books.book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserStatusBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reading", "Читаю"),
                            ("favorite", "Обране"),
                            ("planned", "У планах"),
                            ("dropped", "Кинув"),
                            ("read", "Прочитав"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Поповненя"),
                            ("withdrawal", "Зняття"),
                            ("earn", "Продаж"),
                            ("spend", "Покупка"),
                            ("buy_adv", "Покупка реклами"),
                        ],
                        max_length=40,
                    ),
                ),
                ("time", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["time"],
            },
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("looked", models.IntegerField(default=0)),
                (
                    "income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("sold", models.IntegerField(default=0)),
                ("like", models.IntegerField(default=0)),
                ("in_marks", models.IntegerField(default=0)),
                ("all_characters", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistic",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("font_size", models.IntegerField(default=16)),
                ("font_color", models.CharField(default="#000000", max_length=7)),
                ("background_color", models.CharField(default="#e5e5e5", max_length=7)),
                ("notifications", models.BooleanField(default=True)),
                ("site_news", models.BooleanField(default=True)),
                ("private_messages", models.BooleanField(default=True)),
                ("comments", models.BooleanField(default=True)),
                ("is_adult", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeenBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_seen", models.BooleanField(default=False)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_seen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seen_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "One"),
                            (2, "Two"),
                            (3, "Three"),
                            (4, "Fore"),
                            (5, "Five"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "translation",
                    models.IntegerField(
                        choices=[
                            (1, "One"),
                            (2, "Two"),
                            (3, "Three"),
                            (4, "Fore"),
                            (5, "Five"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="books.book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/users/"),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                ("register_date", models.DateField(auto_now=True)),
                (
                    "commission",
                    models.IntegerField(
                        choices=[(15, "15%"), (12, "12%"), (12, "10%")], default=15
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bought_books",
                    models.ManyToManyField(
                        blank=True, related_name="buyers", to="books.book"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("time", models.DateTimeField(auto_now=True)),
                ("has_seen", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receive_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["time"],
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("date_start", models.DateField(null=True)),
                ("date_finish", models.DateField(null=True)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount",
                        to="books.book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_name", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("is_free", models.BooleanField(default=False)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="books.book",
                    ),
                ),
                ("comments", models.ManyToManyField(blank=True, to="books.comment")),
            ],
        ),
        migrations.CreateModel(
            name="BookMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_status",
                    models.CharField(
                        choices=[
                            ("reading", "Читаю"),
                            ("favorite", "Обране"),
                            ("planned", "У планах"),
                            ("dropped", "Кинув"),
                            ("read", "Прочитав"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_bookmarks",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_marks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="comments",
            field=models.ManyToManyField(blank=True, to="books.comment"),
        ),
        migrations.AddField(
            model_name="book",
            name="fund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="books",
                to="books.fund",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(to="books.genre"),
        ),
        migrations.AddField(
            model_name="book",
            name="photos",
            field=models.ManyToManyField(blank=True, to="books.photo"),
        ),
        migrations.AddField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(blank=True, to="books.tag"),
        ),
        migrations.AddField(
            model_name="book",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("date_start", models.DateField(null=True)),
                ("date_finish", models.DateField(null=True)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adv",
                        to="books.book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "msg_type",
                    models.CharField(
                        choices=[("question", "Питання"), ("answer", "Відповідь")],
                        default="question",
                        max_length=40,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["time"],
            },
        ),
    ]
