# Generated by Django 4.1.7 on 2023-03-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="first",
            new_name="file",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="fourth",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="second",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="third",
        ),
        migrations.AlterField(
            model_name="book",
            name="photos",
            field=models.ManyToManyField(blank=True, null=True, to="books.photo"),
        ),
    ]
