# Generated by Django 4.1.7 on 2023-04-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_restrictions',
            field=models.BooleanField(default=False, verbose_name='Обмеження за вiком 18+'),
        ),
    ]
