# Generated by Django 4.1.7 on 2023-03-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_rename_first_photo_file_remove_photo_fourth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="photos",
        ),
        migrations.AddField(
            model_name="photo",
            name="book",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="books.book",
            ),
            preserve_default=False,
        ),
    ]
