# Generated by Django 4.1.7 on 2023-03-06 19:58

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_remove_book_photos_photo_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="main_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=books.models.upload_to
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="price_chapter",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(blank=True, to="books.genre"),
        ),
        migrations.AddField(
            model_name="book",
            name="subs",
            field=models.ManyToManyField(blank=True, to="books.subscription"),
        ),
    ]
